import EorzeaWeather from 'eorzea-weather';

export const AVAILABLE_LOCALES: Record<string, string> = {
  en: 'English',
  ja: '日本語',
  de: 'Deutsch',
  fr: 'Français',
};

export const HOUR = 175 * 1000;
export const EIGHT_HOURS = 8 * HOUR;
export const ONE_DAY = 24 * HOUR;

export const XIVAPI_DOMAIN = 'https://xivapi.com';

type IconList = {
  [id: string]: number;
};

type MapList = {
  [id: string]: string;
};

export const WEATHER_ICONS = {
  blizzards: 60216,
  clearSkies: 60201,
  clouds: 60203,
  dustStorms: 60211,
  fairSkies: 60202,
  fog: 60204,
  gales: 60206,
  gloom: 60218,
  heatWaves: 60214,
  rain: 60207,
  showers: 60208,
  snow: 60215,
  thunder: 60209,
  thunderstorms: 60210,
  umbralStatic: 60220,
  umbralWind: 60219,
  wind: 60205,
} as IconList;

/*export const AREA_MAPS = {
  laNoscea: '/m/region/region.00.jpg',
  theBlackShroud: '/m/region/region.01.jpg',
  thanalan: '/m/region/region.02.jpg',
  ishgardAndSurroundingAreas: '/backgrounds/ishgard.jpg', // '/m/region/region.03.jpg',
  gyrAbania: '/m/region/region.07.jpg',
  othard: '/backgrounds/othard.jpg', // '/m/region/region.08.jpg',
  norvrandt: '/m/region/region.10.jpg',
} as MapList;*/

export const BACKGROUNDS = {
  amhAraeng: '/backgrounds/amharaeng.jpg',
  azimSteppe: '/backgrounds/azimsteppe.jpg',
  azysLla: '/backgrounds/azyslla.jpg',
  churningMists: '/backgrounds/churningmists.jpg',
  crystarium: '/backgrounds/crystarium.jpg',
  diadem: '/backgrounds/diadem.jpg',
  dravania: '/backgrounds/dravania.jpg',
  eulmore: '/backgrounds/eulmore.jpg',
  fringes: '/backgrounds/fringes.jpg',
  goblet: '/backgrounds/goblet.jpg',
  gridania: '/backgrounds/gridania.jpg',
  gyrAbania: '/backgrounds/gyrabania.jpg',
  ilMheg: '/backgrounds/ilmheg.jpg',
  ishgard: '/backgrounds/ishgard.jpg',
  kholusia: '/backgrounds/kholusia.jpg',
  kugane: '/backgrounds/kugane.jpg',
  lakeland: '/backgrounds/lakeland.jpg',
  lavenderBeds: '/backgrounds/lavenderbeds.jpg',
  limsa: '/backgrounds/limsa.jpg',
  mist: '/backgrounds/mist.jpg',
  morDhona: '/backgrounds/mordhona.jpg',
  othard: '/backgrounds/othard.jpg',
  rakTika: '/backgrounds/raktika.jpg',
  rhalgrs: '/backgrounds/rhalgrs.jpg',
  seaOfClouds: '/backgrounds/seaofclouds.jpg',
  tempest: '/backgrounds/tempest.jpg',
  uldah: '/backgrounds/uldah.jpg',
};

export const ZONE_MAPS = {
  amhAraeng: BACKGROUNDS.amhAraeng, // '/m/n4f3/n4f3.00.jpg',
  azysLla: BACKGROUNDS.azysLla, // '/m/a2f2/a2f2.00.jpg',
  //bozjanSouthernFront: '/m/n4b4/n4b4.01.jpg',
  centralShroud: BACKGROUNDS.gridania, // '/m/f1f1/f1f1.00.jpg',
  centralThanalan: BACKGROUNDS.uldah, // '/m/w1f2/w1f2.00.jpg',
  coerthasCentralHighlands: BACKGROUNDS.ishgard, // '/m/r1f1/r1f1.00.jpg',
  coerthasWesternHighlands: BACKGROUNDS.ishgard, // '/m/r2f1/r2f1.00.jpg',
  eastShroud: BACKGROUNDS.gridania, // '/m/f1f2/f1f2.00.jpg',
  easternLaNoscea: BACKGROUNDS.limsa, // '/m/s1f3/s1f3.01.jpg',
  easternThanalan: BACKGROUNDS.uldah, //'/m/w1f3/w1f3.00.jpg',
  eulmore: BACKGROUNDS.eulmore, // '/m/n4t2/n4t2.02.jpg',
  //eurekaAnemos: '/m/z3fa/z3fa.00.jpg',
  //eurekaHydatos: '/m/z3fd/z3fd.01.jpg',
  //eurekaPagos: '/m/z3fb/z3fb.00.jpg',
  //eurekaPyros: '/m/z3fc/z3fc.00.jpg',
  gridania: BACKGROUNDS.gridania, // '/m/f1t1/f1t1.00.jpg',
  idyllshire: BACKGROUNDS.dravania, // '/m/d2t1/d2t1.00.jpg',
  ilMheg: BACKGROUNDS.ilMheg, // '/m/n4f4/n4f4.00.jpg',
  ishgard: BACKGROUNDS.ishgard, // '/m/r2t1/r2t1.00.jpg',
  kholusia: BACKGROUNDS.kholusia, // '/m/n4f2/n4f2.00.jpg',
  kugane: BACKGROUNDS.kugane, // '/m/e3t1/e3t1.00.jpg',
  lakeland: BACKGROUNDS.lakeland, // '/m/n4f1/n4f1.00.jpg',
  limsaLominsa: BACKGROUNDS.limsa, // '/m/s1t1/s1t1.01.jpg',
  lowerLaNoscea: BACKGROUNDS.limsa, // '/m/s1f2/s1f2.00.jpg',
  middleLaNoscea: BACKGROUNDS.limsa, // '/m/s1f1/s1f1.00.jpg',
  mist: BACKGROUNDS.mist, // '/m/s1h1/s1h1.01.jpg',
  morDhona: BACKGROUNDS.morDhona, // '/m/l1f1/l1f1.01.jpg',
  northShroud: BACKGROUNDS.gridania, // '/m/f1f4/f1f4.00.jpg',
  northernThanalan: BACKGROUNDS.uldah, // '/m/w1f5/w1f5.00.jpg',
  outerLaNoscea: BACKGROUNDS.limsa, // '/m/s1f6/s1f6.00.jpg',
  rhalgrsReach: BACKGROUNDS.rhalgrs, // '/m/g3t1/g3t1.00.jpg',
  shirogane: BACKGROUNDS.kugane, // '/m/e1h1/e1h1.01.jpg',
  southShroud: BACKGROUNDS.gridania, // '/m/f1f3/f1f3.00.jpg',
  southernThanalan: BACKGROUNDS.uldah, // '/m/w1f4/w1f4.01.jpg',
  theAzimSteppe: BACKGROUNDS.azimSteppe, // '/m/e3f3/e3f3.00.jpg',
  theChurningMists: BACKGROUNDS.churningMists, // '/m/d2f3/d2f3.00.jpg',
  theCrystarium: BACKGROUNDS.crystarium, // '/m/n4t1/n4t1.00.jpg',
  theDiadem: BACKGROUNDS.diadem, // '/m/a2fc/a2fc.00.jpg',
  theDravanianForelands: BACKGROUNDS.dravania, // '/m/d2f1/d2f1.00.jpg',
  theDravanianHinterlands: BACKGROUNDS.dravania, // '/m/d2f2/d2f2.00.jpg',
  theFringes: BACKGROUNDS.fringes, // '/m/g3f1/g3f1.00.jpg',
  theGoblet: BACKGROUNDS.goblet, // '/m/w1h1/w1h1.01.jpg',
  theLavenderBeds: BACKGROUNDS.lavenderBeds, // '/m/f1h1/f1h1.01.jpg',
  theLochs: BACKGROUNDS.gyrAbania, // '/m/g3f3/g3f3.00.jpg',
  thePeaks: BACKGROUNDS.gyrAbania, // '/m/g3f2/g3f2.00.jpg',
  theRaktikaGreatwood: BACKGROUNDS.rakTika, // '/m/n4f5/n4f5.00.jpg',
  theRubySea: BACKGROUNDS.othard, // '/m/e3f1/e3f1.00.jpg',
  theSeaOfClouds: BACKGROUNDS.seaOfClouds, // '/m/a2f1/a2f1.00.jpg',
  theTempest: BACKGROUNDS.tempest, // '/m/n4f6/n4f6.00.jpg',
  uldah: BACKGROUNDS.uldah, // '/m/w1t1/w1t1.01.jpg',
  upperLaNoscea: BACKGROUNDS.limsa, // '/m/s1f5/s1f5.00.jpg',
  westernLaNoscea: BACKGROUNDS.limsa, // '/m/s1f4/s1f4.00.jpg',
  westernThanalan: BACKGROUNDS.uldah, // '/m/w1f1/w1f1.00.jpg',
  wolvesDenPier: BACKGROUNDS.limsa, // '/m/s1p1/s1p1.00.jpg',
  yanxia: BACKGROUNDS.othard, // '/m/e3f2/e3f2.00.jpg',
  //zadnor: '/m/n4b6/n4b6.01.jpg',
} as MapList;

export const EORZEA_ZONE_LIST = [
  EorzeaWeather.ZONE_AMH_ARAENG,
  EorzeaWeather.ZONE_AZYS_LLA,
  EorzeaWeather.ZONE_BOZJAN_SOUTHERN_FRONT,
  EorzeaWeather.ZONE_CENTRAL_SHROUD,
  EorzeaWeather.ZONE_CENTRAL_THANALAN,
  EorzeaWeather.ZONE_COERTHAS_CENTRAL_HIGHLANDS,
  EorzeaWeather.ZONE_COERTHAS_WESTERN_HIGHLANDS,
  EorzeaWeather.ZONE_EAST_SHROUD,
  EorzeaWeather.ZONE_EASTERN_LA_NOSCEA,
  EorzeaWeather.ZONE_EASTERN_THANALAN,
  EorzeaWeather.ZONE_EULMORE,
  EorzeaWeather.ZONE_EUREKA_ANEMOS,
  EorzeaWeather.ZONE_EUREKA_HYDATOS,
  EorzeaWeather.ZONE_EUREKA_PAGOS,
  EorzeaWeather.ZONE_EUREKA_PYROS,
  EorzeaWeather.ZONE_GRIDANIA,
  EorzeaWeather.ZONE_IDYLLSHIRE,
  EorzeaWeather.ZONE_IL_MHEG,
  EorzeaWeather.ZONE_ISHGARD,
  EorzeaWeather.ZONE_KHOLUSIA,
  EorzeaWeather.ZONE_KUGANE,
  EorzeaWeather.ZONE_LAKELAND,
  EorzeaWeather.ZONE_LIMSA_LOMINSA,
  EorzeaWeather.ZONE_LOWER_LA_NOSCEA,
  EorzeaWeather.ZONE_MIDDLE_LA_NOSCEA,
  EorzeaWeather.ZONE_MIST,
  EorzeaWeather.ZONE_MOR_DHONA,
  EorzeaWeather.ZONE_NORTH_SHROUD,
  EorzeaWeather.ZONE_NORTHERN_THANALAN,
  EorzeaWeather.ZONE_OUTER_LA_NOSCEA,
  EorzeaWeather.ZONE_RHALGRS_REACH,
  EorzeaWeather.ZONE_SHIROGANE,
  EorzeaWeather.ZONE_SOUTH_SHROUD,
  EorzeaWeather.ZONE_SOUTHERN_THANALAN,
  EorzeaWeather.ZONE_THE_AZIM_STEPPE,
  EorzeaWeather.ZONE_THE_CHURNING_MISTS,
  EorzeaWeather.ZONE_THE_CRYSTARIUM,
  EorzeaWeather.ZONE_THE_DIADEM,
  EorzeaWeather.ZONE_THE_DRAVANIAN_FORELANDS,
  EorzeaWeather.ZONE_THE_DRAVANIAN_HINTERLANDS,
  EorzeaWeather.ZONE_THE_FRINGES,
  EorzeaWeather.ZONE_THE_GOBLET,
  EorzeaWeather.ZONE_THE_LAVENDER_BEDS,
  EorzeaWeather.ZONE_THE_LOCHS,
  EorzeaWeather.ZONE_THE_PEAKS,
  EorzeaWeather.ZONE_THE_RAKTIKA_GREATWOOD,
  EorzeaWeather.ZONE_THE_RUBY_SEA,
  EorzeaWeather.ZONE_THE_SEA_OF_CLOUDS,
  EorzeaWeather.ZONE_THE_TEMPEST,
  EorzeaWeather.ZONE_ULDAH,
  EorzeaWeather.ZONE_UPPER_LA_NOSCEA,
  EorzeaWeather.ZONE_WESTERN_LA_NOSCEA,
  EorzeaWeather.ZONE_WESTERN_THANALAN,
  EorzeaWeather.ZONE_WOLVES_DEN_PIER,
  EorzeaWeather.ZONE_YANXIA,
  EorzeaWeather.ZONE_ZADNOR,
];
